In [2]:
# cerner_2^5_2019
import numpy as np 
  
# input two matrices 
mat1 = ([4, 7, 1, 4],[5, 4, 2, 8],[5, 12, 2, 5], [4, 6, 2, 4]) 
mat2 = ([0, 6, 3, 2],[5, 9, 8, 4],[2, 55, 6, 4], [2, 3, 7, 2]) 
  
# returns the dot product 
result = np.dot(mat1,mat2) 
  
# print resulted matrix 
print(result)

[[ 45 154 102  48]
 [ 40 200 115  50]
 [ 74 263 158  76]
 [ 42 200 100  48]]
